//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmMini.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADDRESS
    {
        public int ADDRESS_CODE { get; set; }
        public string OWNER { get; set; }
        public Nullable<int> ADDRESS_TYPE_ID { get; set; }
        public Nullable<int> COMPANY_CODE { get; set; }
        public Nullable<int> CONTACT_CODE { get; set; }
        public Nullable<int> REGION_CODE { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public string COUNTY { get; set; }
        public string CITY { get; set; }
        public string COUNTY1 { get; set; }
        public string COUNTY2 { get; set; }
        public string POSTCODE { get; set; }
        public string GPS_LATITUDE { get; set; }
        public string GPS_LONGITUDE { get; set; }
        public Nullable<int> DISTANCE { get; set; }
        public Nullable<System.DateTime> LASTUP_DATE { get; set; }
        public string LAST_UPDATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
    }
}
