//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmMini.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CITEM
    {
        public int CODE { get; set; }
        public int ROW_ORDER_NO { get; set; }
        public string EXP_TR { get; set; }
        public string EXP_EN { get; set; }
        public string EXP_GR { get; set; }
        public string ITEM2 { get; set; }
        public string ITEM3 { get; set; }
        public string ITEM4 { get; set; }
    }
}
