//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmMini.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY
    {
        public int COMPANY_CODE { get; set; }
        public string UPPER_COMPANY_CODE { get; set; }
        public string COMPANY_COMMERCIAL_CODE { get; set; }
        public int COMPANY_REPRESENT_CODE { get; set; }
        public string COMPANY_NAME { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<int> SECTOR { get; set; }
        public Nullable<int> COMPANY_SPECIAL_TYPE { get; set; }
        public Nullable<int> PHONE { get; set; }
        public Nullable<int> FAX { get; set; }
        public string MAIL { get; set; }
        public string WEBADDRESS { get; set; }
        public Nullable<int> COMPANY_REFERANCE { get; set; }
        public Nullable<int> COMPANY_TYPE { get; set; }
        public Nullable<System.DateTime> FOUNDATION_DATE { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<int> COMPANY_REGION { get; set; }
        public string TAX_DEPARTMENT { get; set; }
        public string TAX_NO { get; set; }
        public Nullable<int> CURRENCY_TYPE { get; set; }
        public Nullable<int> INVOICE_ADDRESS_CODE { get; set; }
        public Nullable<int> SHIPPING_ADDRESS_CODE { get; set; }
        public string COMPANY_OWNER { get; set; }
        public string PAYMENT_DAY { get; set; }
        public Nullable<int> PAYMENT_TYPE { get; set; }
        public Nullable<decimal> DISCOUNT_RATIO { get; set; }
        public string PAYMENT_PERSON { get; set; }
        public string PURCHASE_PERSON { get; set; }
        public string WAREHOUSE_PERSON { get; set; }
        public Nullable<decimal> ENDORSEMENT { get; set; }
        public string CALCULATE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public System.DateTime LAST_UPDATE { get; set; }
        public string LAST_UPDATE_USER { get; set; }
    }
}
