//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmMini.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACT
    {
        public int CONTACT_CODE { get; set; }
        public int COMPANY_CODE { get; set; }
        public int CONTACT_REPRESENT_CODE { get; set; }
        public string NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string SURNAME { get; set; }
        public Nullable<System.DateTime> BIRTHDATE { get; set; }
        public string NICNAME { get; set; }
        public string SPACIAL_CODE { get; set; }
        public Nullable<int> DEPARTMENT { get; set; }
        public Nullable<int> TITLE { get; set; }
        public string MAIL { get; set; }
        public string MSN { get; set; }
        public string PERSONALWEBADDRESS { get; set; }
        public Nullable<int> CONTACT_REFERANCE { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<int> ISSPACIAL { get; set; }
        public string LAST_STATE { get; set; }
        public Nullable<int> EDUCATION { get; set; }
        public Nullable<int> LAST_FNISHED_SCHOOL { get; set; }
        public Nullable<int> COLOR { get; set; }
        public Nullable<int> INVOICE_ADDRESS_CODE { get; set; }
        public string SPEC1 { get; set; }
        public string SPEC2 { get; set; }
        public string SPEC3 { get; set; }
        public Nullable<int> FTEEM { get; set; }
        public Nullable<int> ISMARRIED { get; set; }
        public Nullable<System.DateTime> ANNIVERSARY_DATE { get; set; }
        public string PARTNER_NAME { get; set; }
        public string PARTNER_MIDDLE_NAME { get; set; }
        public string PARTNER_SURNAME { get; set; }
        public Nullable<int> CHILD_COUNT { get; set; }
        public Nullable<int> MALE_CHILD_COUNT { get; set; }
        public Nullable<int> FEMALE_CHILD_COUNT { get; set; }
        public Nullable<int> HAVE_HOME { get; set; }
        public Nullable<int> HOME_RATING { get; set; }
        public Nullable<System.DateTime> LAST_MEETING_DATE { get; set; }
        public Nullable<System.DateTime> LAST_OPPORTUNITY_DATE { get; set; }
        public Nullable<System.DateTime> LAST_OFFER_DATE { get; set; }
        public Nullable<System.DateTime> LAST_WAYBILL_DATE { get; set; }
        public Nullable<System.DateTime> LAST_INVOICE_DATE { get; set; }
        public string LAST_UPDATE_USER { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public byte[] BPICTURE { get; set; }
        public Nullable<int> SEXUALITY { get; set; }
        public Nullable<int> PRETITLE { get; set; }
        public Nullable<int> ADDRESS { get; set; }
    }
}
