//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmMini.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURTYPE
    {
        public string CUR_NAME { get; set; }
        public string CUR_SYMBOL { get; set; }
        public Nullable<int> ROW_ORDER_NO { get; set; }
        public Nullable<int> CUR_EXT { get; set; }
    }
}
