//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmMini.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUPDE
    {
        public int CODE { get; set; }
        public string EXP_TR { get; set; }
        public string EXP_EN { get; set; }
        public string EXP_GR { get; set; }
        public int UPPER_EXIST { get; set; }
        public string UPPER_CAPTION { get; set; }
        public Nullable<int> UPPER_FIH_NO { get; set; }
        public Nullable<int> UPPER_GROUP_CODE { get; set; }
        public Nullable<int> MTYPE { get; set; }
    }
}
