//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmMini.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONE
    {
        public int PHONE_CODE { get; set; }
        public Nullable<int> PHONE_TYPE_ID { get; set; }
        public string PHONE_NUMBER { get; set; }
        public string AREA_CODE { get; set; }
        public string COUNTRY_CODE { get; set; }
        public Nullable<int> COMPANY_CODE { get; set; }
        public Nullable<int> CONTACT_CODE { get; set; }
        public string OWNER { get; set; }
        public Nullable<int> REGION_CODE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> LASTUP_DATE { get; set; }
        public string LAST_UPDATE_USER { get; set; }
        public Nullable<int> ADDRESS_CODE { get; set; }
        public string INTERNAL_CODE { get; set; }
    }
}
