//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmMini.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECT
    {
        public int PROJECT_CODE { get; set; }
        public string NAME { get; set; }
        public int COMPANY_CODE { get; set; }
        public int CONTACT_CODE { get; set; }
        public int OPPORTUNITY_CODE { get; set; }
        public int CONTRACT_CODE { get; set; }
        public System.DateTime DOCUMENT_DATE { get; set; }
        public Nullable<System.DateTime> SDATE { get; set; }
        public Nullable<System.DateTime> EDATE { get; set; }
        public string APPOINTED_USER_CODE { get; set; }
        public Nullable<System.DateTime> CLOSED_DATE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public System.DateTime LAST_UPDATE { get; set; }
        public string LAST_UPDATE_USER { get; set; }
        public Nullable<int> ROW_ORDER_NO { get; set; }
        public string STOK_NAME { get; set; }
        public Nullable<System.DateTime> RS_DATE { get; set; }
        public Nullable<int> CLOSED_USER { get; set; }
    }
}
