//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmMini.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VdbSoftEntities : DbContext
    {
        public VdbSoftEntities()
            : base("name=VdbSoftEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACTIVITY> ACTIVITies { get; set; }
        public virtual DbSet<ADDRESS> ADDRESSes { get; set; }
        public virtual DbSet<CITEM> CITEMS { get; set; }
        public virtual DbSet<CITY> CITies { get; set; }
        public virtual DbSet<CITY2> CITY2 { get; set; }
        public virtual DbSet<COMPANY> COMPANies { get; set; }
        public virtual DbSet<CONTACT> CONTACTs { get; set; }
        public virtual DbSet<CURTYPE> CURTYPEs { get; set; }
        public virtual DbSet<GROUPDE> GROUPDES { get; set; }
        public virtual DbSet<GROUP> GROUPS { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<CUR> CURs { get; set; }
        public virtual DbSet<PROJECT> PROJECTS { get; set; }
        public virtual DbSet<COUNTRY> COUNTRies { get; set; }
        public virtual DbSet<PHONE> PHONEs { get; set; }
    }
}
